# https://cloud.google.com/appengine/docs/the-appengine-environments#comparing_high-level_features
# https://cloud.google.com/appengine/docs/standard

runtime: java17
env: flex

automatic_scaling:
  max_num_instances: 1

network:
  session_affinity: true

env_variables:
  MAIL_HOST: $MAIL_HOST
  MAIL_USERNAME: $MAIL_USERNAME
  MAIL_PASSWORD: $MAIL_PASSWORD
  POSTGRESQL_URL: $POSTGRESQL_URL
  POSTGRESQL_USERNAME: $POSTGRESQL_USERNAME
  POSTGRESQL_PASSWORD: $POSTGRESQL_PASSWORD